sudo: false

language: java

jdk:
- oraclejdk8

branches:
  only:
  - develop
  - master
  - "/^v[0-9].*/"

before_script:
- export TZ=Europe/Berlin

script: mvn clean verify

deploy:
  provider: releases
  api_key:
    secure: xEWg4ze7vhEWTyhMGVKbrVq1a/2v8nY0ooMKxMQlDWed1XxRv/JLJAl8CUYbtI6Z7Kv7itucVjYz8td6059X8v1YsdOcfXPH3OtR7VZlS/p+ZTh7nWANz3J3fjoFDcVR7VaKpiDAkP+Acr8D87rLtssiMRnc72mbemGfLMoC1x0d869WQ4p+4ROgpl+hWYxFReRXx7cRARHPddfh+NHrvwwCA4waKB9ch+kWPybqujIDrk8Rz1j4FfBacU+Vo58BqD2iuel3O1E/MHHAnyq6ZUU5npJnuYK/BQi9jN7DBfQ6YEU3vCfY1pmee+6vj4F+2deRBfiSWX15bwKVDHnNE0263oQNRhW7LMRW7JGe4+Gq8A0Lz/PBD0VxZbtrH6h4/4QbMuSARA9+Ooc0NOss0rHKnymfz7S+WUL1l/7El7oSiiFpJXNzTsAG1ckPnaHSpsDq2Sh/IQyxuuee0Y5l1dJYD9b2XpZSRSKqfVsjalZAZwnB2ueEg9NOaVHKDFJOEdxvSSU/41ZeYIA+UQ7Ypy+7nIOssPD7qnSIXnLCxlJ3Fuhd9kfPSH0L5kTM+Sg237X9i2hzRjEophUuUzvLcCCHoQESIrlefWlMcoeDHGxO9XRBdaaI7hLah36kEq+7OWLDqh86O1493a4jBGkIY+lnnOHvzUMh/Lhv7v71F/g=
  file: "./target/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    repo: mathisdt/trackselect
